# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'QingHuaTestDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QingHuaTestDemo

  target 'QingHuaTestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QingHuaTestDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'AFNetworking', '>= 3.0'
  pod 'MJExtension'
  pod 'PLMediaStreamingKit'
  pod 'PLPlayerKit'
end
